import type { ThemePreset } from './config'

export const PRESET_TOKENS: Record<ThemePreset, Record<string, string>> = {
  light: {
    '--enlb-overlay-bg': 'rgba(0, 0, 0, 0.6)',
    '--enlb-surface-bg': '#fff',
    '--enlb-text': '#1f1f1f',
    '--enlb-title': '#1f1f1f',
    '--enlb-cta-bg': '#1a73e8',
    '--enlb-cta-text': '#fff',
    '--enlb-secondary-cta-bg': 'transparent',
    '--enlb-secondary-cta-text': '#1a73e8',
    '--enlb-border': '#e0e0e0',
    '--enlb-radius': '8px',
    '--enlb-max-width': '900px',
    '--enlb-font-family': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  dark: {
    '--enlb-overlay-bg': 'rgba(0, 0, 0, 0.7)',
    '--enlb-surface-bg': '#1f1f1f',
    '--enlb-text': '#e0e0e0',
    '--enlb-title': '#ffffff',
    // Inverted CTA: white button + dark text (matches forest's pattern).
    '--enlb-cta-bg': '#ffffff',
    '--enlb-cta-text': '#1f1f1f',
    '--enlb-secondary-cta-bg': 'transparent',
    '--enlb-secondary-cta-text': '#8ab4f8',
    '--enlb-border': '#3a3a3a',
    '--enlb-radius': '8px',
    '--enlb-max-width': '900px',
    '--enlb-font-family': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  brand: {
    '--enlb-overlay-bg': 'rgba(0, 20, 10, 0.7)',
    '--enlb-surface-bg': '#003d24',
    '--enlb-text': '#f0f7f3',
    '--enlb-title': '#ffffff',
    '--enlb-cta-bg': '#00875a',
    '--enlb-cta-text': '#ffffff',
    '--enlb-secondary-cta-bg': 'transparent',
    '--enlb-secondary-cta-text': '#6dd5a8',
    '--enlb-border': '#1a5c3a',
    '--enlb-radius': '8px',
    '--enlb-max-width': '900px',
    '--enlb-font-family': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  forest: {
    '--enlb-overlay-bg': 'rgba(0, 20, 10, 0.7)',
    '--enlb-surface-bg': '#006537',
    '--enlb-text': '#ffffff',
    '--enlb-title': '#ffffff',
    '--enlb-cta-bg': '#ffffff',
    '--enlb-cta-text': '#006537',
    '--enlb-secondary-cta-bg': 'transparent',
    '--enlb-secondary-cta-text': '#ffffff',
    '--enlb-border': 'rgba(255, 255, 255, 0.25)',
    '--enlb-radius': '6px',
    '--enlb-max-width': '900px',
    '--enlb-font-family': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  sky: {
    '--enlb-overlay-bg': 'rgba(0, 0, 0, 0.6)',
    '--enlb-surface-bg': '#8DBBDC',
    '--enlb-text': '#191919',
    '--enlb-title': '#191919',
    '--enlb-cta-bg': '#000000',
    '--enlb-cta-text': '#ffffff',
    '--enlb-secondary-cta-bg': 'transparent',
    '--enlb-secondary-cta-text': '#000000',
    '--enlb-border': 'rgba(0, 0, 0, 0.15)',
    '--enlb-radius': '6px',
    '--enlb-max-width': '900px',
    '--enlb-font-family': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
}
